;==========================================================================
; Font index exported ven. janv. 13 2012 by FontIO.cpp 110 2011-06-07 11:26:40Z gascuel $ 
;==========================================================================
aa_font90_chars		EQU	.14
aa_font90_firstChar	EQU	'.'
aa_font90_lastChar	EQU	';'
;
aa_font90_idx:
			DW	aa_font90_bits + 0x0000	; . dot
			DW	aa_font90_bits + 0x0028	; / slash
			DW	aa_font90_bits + 0x003B	; 0 0
			DW	aa_font90_bits + 0x0112	; 1 1
			DW	aa_font90_bits + 0x0193	; 2 2
			DW	aa_font90_bits + 0x026E	; 3 3
			DW	aa_font90_bits + 0x037B	; 4 4
			DW	aa_font90_bits + 0x0432	; 5 5
			DW	aa_font90_bits + 0x04FD	; 6 6
			DW	aa_font90_bits + 0x061F	; 7 7
			DW	aa_font90_bits + 0x06D3	; 8 8
			DW	aa_font90_bits + 0x080F	; 9 9
			DW	aa_font90_bits + 0x0925	; : colon
			DW	aa_font90_bits + 0x09A7	; ; semicolon
			DW	aa_font90_bits + 0x0A71	; END OF INDEX
