;=============================================================================
;
;   File colorschemes.inc
;
;=============================================================================

; Dive mode
; Standard
#DEFINE color_scheme_divemode_mask1     color_green
#DEFINE color_scheme_divemode_std1      color_white

; Redish
#DEFINE color_scheme_divemode_mask2     color_red
#DEFINE color_scheme_divemode_std2      color_orange

; greenish
#DEFINE color_scheme_divemode_mask3     color_cyan
#DEFINE color_scheme_divemode_std3      color_green

; blueish
#DEFINE color_scheme_divemode_mask4     color_lightblue
#DEFINE color_scheme_divemode_std4      color_blue