;=============================================================================
;
;   File ghostwriter.inc
;
;
;   Copyright (c) 2011, JD Gascuel, HeinrichsWeikamp, all right reserved.
;=============================================================================
; HISTORY
;  2011-11-27 : [mH] Creation

	extern 	store_dive_data
	extern	ghostwriter_end_dive
	extern	ghostwriter_short_header
	extern	update_battery_registers
	extern	do_logoffset_common_write
	extern	do_logoffset_common_read

 