;=============================================================================
;
;   File math.inc
;
;
;   Copyright (c) 2011, JD Gascuel, HeinrichsWeikamp, all right reserved.
;=============================================================================
; HISTORY
;  2011-08-03 : [mH] moving from OSTC code

	extern	convert_time
	extern	div16
	extern	sub16
	extern	subU16
	extern	mult16x16
	extern	div16x16
	extern	div32x16
;	extern	isr_mult16x16
	extern	isr_shift_C31
	extern	isr_unsigned_mult16x16
	extern	isr_signed_mult16x16
