;=============================================================================
;
;   File mcp.inc
;
;
;   Copyright (c) 2011, JD Gascuel, HeinrichsWeikamp, all right reserved.
;=============================================================================
; HISTORY
;  2012-09-03 : [mH] creation

 extern  mcp_reset_rssi          ; Setup RX for RSSI mode
 extern  mcp_reset               ; Setup RX (Normal mode)

