;=============================================================================
;
;   File ms5541.inc
;
;
;   Copyright (c) 2011, JD Gascuel, HeinrichsWeikamp, all right reserved.
;=============================================================================
; HISTORY
;  2011-08-04 : [mH] moving from OSTC code

	extern	calculate_compensation
	extern	get_pressure_start
	extern	get_pressure_value
	extern	get_temperature_start
	extern	get_temperature_value
	extern 	get_calibration_data
