;=============================================================================
;
;   File start.inc
;
;
;   Copyright (c) 2011, JD Gascuel, HeinrichsWeikamp, all right reserved.
;=============================================================================
; HISTORY
;  2011-08-06 : [mH] moving from OSTC code

	extern	restart
	extern	restart_set_modes_and_flags
	extern	start
	extern	power_on_return	